version: '3'

services:
  db:
    image: postgres
    volumes:
      - "./database:/var/lib/postgresql/data"
  backend:
    build: ./
    command: sh docker-entrypoint.sh
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - db