# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171014_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='ulist',
        ),
        migrations.AddField(
            model_name='list',
            name='listItems',
            field=models.ManyToManyField(to='api.ListItem'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='state',
            field=models.CharField(choices=[('DONE', 'Done'), ('UNDONE', 'Undone')], default='UNDONE', max_length=255),
        ),
    ]
