# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171017_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='listItems',
            new_name='list_items',
        ),
    ]
