# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171017_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='users',
            field=models.ManyToManyField(default=[1], to='api.User'),
        ),
    ]
