# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171020_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='users',
            field=models.ManyToManyField(to='api.User'),
        ),
    ]
