# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171021_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='list_items',
        ),
        migrations.AddField(
            model_name='listitem',
            name='task_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='api.TaskList'),
        ),
    ]
