# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20171021_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
