# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_listitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='owner',
        ),
        migrations.AddField(
            model_name='listitem',
            name='owners',
            field=models.ManyToManyField(default=None, related_name='list_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='owners',
            field=models.ManyToManyField(related_name='task_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
