# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171025_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='owners',
            field=models.ManyToManyField(related_name='list_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
